DibiDibiDeep/Final-back

src/main/java/com/example/finalproj/googleLogin/controller/LoginController.java
src/main/java/com/example/finalproj/googleLogin/model/dto/Google/GoogleInfResponse.java
src/main/java/com/example/finalproj/googleLogin/model/dto/Google/GoogleRequest.java
src/main/java/com/example/finalproj/googleLogin/model/dto/Google/GoogleResponse.java
src/main/java/com/example/finalproj/member/controller/FinalController.java
src/main/java/com/example/finalproj/member/model/dao/MemberDao.java
src/main/java/com/example/finalproj/member/model/dto/MemberDto.java
src/main/java/com/example/finalproj/memo/controller/MemoController.java
src/main/java/com/example/finalproj/memo/model/dao/MemoDao.java
src/main/java/com/example/finalproj/memo/model/dto/MemoDto.java
src/main/resources/mybatis/mapper/Member.xml
src/main/resources/mybatis/mapper/Memo.xml
src/main/resources/static/script/memoScript.js

folder commit

---

Dockerfile

docekrfile commit

---

mong-back-revision8.json

[FEATURE][taskdefinition] edit commit

---

mong-back-revision9.json

rds update json commit

---

src/main/java/com/example/finalproj/config/DatabaseInitializer.java
src/main/resources/init.sql

init.sql추가 databaseInitializer추가 commit

init.sql추가 databaseInitializer추가 commit

---

src/main/java/com/example/finalproj/config/DatabaseInitializer.java
src/main/resources/application.yml

rds 제외하고 merge

---

src/main/resources/application.yml

update: application.yml

---

http/calendarPhotoInfo.http
src/main/java/com/example/finalproj/CalendarPhoto/controller/CalendarPhotoController.java
src/main/java/com/example/finalproj/CalendarPhoto/service/CalendarPhotoService.java
src/main/java/com/example/finalproj/CalendarPhotoInf/controller/CalendarPhotoInfController.java
src/main/java/com/example/finalproj/CalendarPhotoInf/entity/CalendarPhotoInf.java
src/main/java/com/example/finalproj/CalendarPhotoInf/repository/CalendarPhotoInfRepository.java
src/main/java/com/example/finalproj/CalendarPhotoInf/service/CalendarPhotoInfService.java
src/main/java/com/example/finalproj/FinalProjApplication.java
src/main/java/com/example/finalproj/calendar/entity/Calendar.java
src/main/java/com/example/finalproj/calendar/repository/CalendarRepository.java
src/main/java/com/example/finalproj/config/RestTemplateConfig.java
src/main/java/com/example/finalproj/ml/service/MLEventListener.java
src/main/java/com/example/finalproj/ml/service/MLProcessingCompletedEvent.java
src/main/java/com/example/finalproj/ml/service/MLService.java
src/main/resources/application.yml

##주요내용
가정통신문을 이미지로 저장시 ml로 전송 -> ml결과값을 리턴 받음 -> 결과 값을 분석하여 일정(calendar)에 저장

[FEATURE][calendarPhotoInf] To ML and Inf calendar  SAVE

---

http/book.http
src/main/java/com/example/finalproj/Book/controller/BookController.java
src/main/java/com/example/finalproj/Book/entity/Book.java
src/main/java/com/example/finalproj/Book/repository/BookRepository.java
src/main/java/com/example/finalproj/Book/service/BookService.java
src/main/java/com/example/finalproj/BookInf/controller/BookInfController.java
src/main/java/com/example/finalproj/BookInf/entity/BookInf.java
src/main/java/com/example/finalproj/BookInf/repository/BookInfRepository.java
src/main/java/com/example/finalproj/BookInf/service/BookInfService.java
src/main/java/com/example/finalproj/Page/controller/PageController.java
src/main/java/com/example/finalproj/Page/entity/Page.java
src/main/java/com/example/finalproj/Page/repository/PageRepository.java
src/main/java/com/example/finalproj/Page/service/PageService.java

[FEATURE][books3]book coverPath S3 upload test ok

---

src/main/java/com/example/finalproj/CalendarPhotoInf/service/CalendarPhotoInfService.java
src/main/java/com/example/finalproj/calendar/entity/Calendar.java
src/main/java/com/example/finalproj/config/WebConfig.java

- ClassCastException: Integer를 String으로 캐스팅하려고 할 때 발생하는 오류 해결
- table명이 calendar인데 Calendar로 불러서 발생하는 오류 해결 
- 임시 origin 추가 테스트 (삭제 필요)

[FIX] ClassCastException, table대문자 수정, dev용 임시 origin 추가

---

build.gradle
src/main/java/com/example/finalproj/config/SecurityConfig.java

[Branch][feature/springsecurity]
- google 로그인 시 인증 기능 구현
- 의존성추가, securityconfig
스크린샷을 첨부해주세요.
- #34 

[기능 생성] SpringSecurity 작업 진행중

---

http/book.http
http/bookInf.http
http/page.http
src/main/java/com/example/finalproj/Book/service/BookService.java
src/main/java/com/example/finalproj/Page/controller/PageController.java
src/main/java/com/example/finalproj/Page/service/PageService.java
src/main/java/com/example/finalproj/ml/service/BookMLEventListener.java
src/main/java/com/example/finalproj/ml/service/BookMLProcessingCompletedEvent.java
src/main/java/com/example/finalproj/ml/service/MLService.java

[Branch][feature/imagePath]
- page의 imagePath를 s3에 저장하게 만들려고
- page의 imagePath를 s3에 등록 및 ml에 쏴주고 리턴하면 결과 자동으로 저장
스크린샷을 첨부해주세요.
- [기능생성] s3에 imagePath 저장 및 ml에 쏴주고 리턴하면 결과 자동으로 저장

[기능 생성] book,page,bookInf ImagePath save in s3, ml return to save

---

src/main/java/com/example/finalproj/BabyPhoto/controller/BabyPhotoController.java
src/main/java/com/example/finalproj/BabyPhoto/entity/BabyPhoto.java
src/main/java/com/example/finalproj/BabyPhoto/repository/BabyPhotoRepository.java
src/main/java/com/example/finalproj/BabyPhoto/service/BabyPhotoService.java
src/main/java/com/example/finalproj/Book/controller/BookController.java
src/main/java/com/example/finalproj/Book/entity/Book.java
src/main/java/com/example/finalproj/Book/repository/BookRepository.java
src/main/java/com/example/finalproj/Book/service/BookService.java
src/main/java/com/example/finalproj/BookInf/controller/BookInfController.java
src/main/java/com/example/finalproj/BookInf/entity/BookInf.java
src/main/java/com/example/finalproj/BookInf/repository/BookInfRepository.java
src/main/java/com/example/finalproj/BookInf/service/BookInfService.java
src/main/java/com/example/finalproj/Page/controller/PageController.java
src/main/java/com/example/finalproj/Page/entity/Page.java
src/main/java/com/example/finalproj/Page/repository/PageRepository.java
src/main/java/com/example/finalproj/Page/service/PageService.java
src/main/java/com/example/finalproj/baby/controller/BabyController.java
src/main/java/com/example/finalproj/baby/entity/Baby.java
src/main/java/com/example/finalproj/baby/repository/BabyRepository.java
src/main/java/com/example/finalproj/baby/service/BabyService.java
src/main/java/com/example/finalproj/memo/controller/MemoController.java
src/main/java/com/example/finalproj/memo/entity/Memo.java
src/main/java/com/example/finalproj/memo/repository/MemoRepository.java
src/main/java/com/example/finalproj/memo/service/MemoService.java
src/main/java/com/example/finalproj/ml/service/BookMLEventListener.java
src/main/java/com/example/finalproj/ml/service/BookMLProcessingCompletedEvent.java
src/main/java/com/example/finalproj/ml/service/MLEventListener.java
src/main/java/com/example/finalproj/ml/service/MLProcessingCompletedEvent.java
src/main/java/com/example/finalproj/ml/service/MLService.java

[Branch][feature/hyunCodeFix]
- 코드에 한글로 된 설명주석을 다는데 딴 분들이 보기 편해서
-  baby, babyPhoto, memo, book, bookInf, page, ml.service 코드들에 한글로 된 설명주석을 담
스크린샷을 첨부해주세요.
- 코드에 한글로 된 설명주석을 추가했음

주석 추가: api 기능 설명 주석

---

http/alim.http
src/main/java/com/example/finalproj/Alim/controller/AlimController.java
src/main/java/com/example/finalproj/Alim/repository/AlimRepository.java
src/main/java/com/example/finalproj/Alim/service/AlimService.java
src/main/java/com/example/finalproj/AlimInf/controller/AlimInfController.java
src/main/java/com/example/finalproj/AlimInf/repository/AlimInfRepository.java
src/main/java/com/example/finalproj/AlimInf/service/AlimInfService.java
src/main/java/com/example/finalproj/CalendarPhoto/controller/CalendarPhotoController.java
src/main/java/com/example/finalproj/CalendarPhoto/repository/CalendarPhotoRepository.java
src/main/java/com/example/finalproj/CalendarPhoto/service/CalendarPhotoService.java
src/main/java/com/example/finalproj/CalendarPhotoInf/controller/CalendarPhotoInfController.java
src/main/java/com/example/finalproj/CalendarPhotoInf/repository/CalendarPhotoInfRepository.java
src/main/java/com/example/finalproj/CalendarPhotoInf/service/CalendarPhotoInfService.java
src/main/java/com/example/finalproj/TodaySum/controller/TodaySumController.java
src/main/java/com/example/finalproj/TodaySum/repository/TodaySumRepository.java
src/main/java/com/example/finalproj/TodaySum/service/TodaySumService.java
src/main/java/com/example/finalproj/calendar/controller/CalendarController.java
src/main/java/com/example/finalproj/calendar/repository/CalendarRepository.java
src/main/java/com/example/finalproj/calendar/service/CalendarService.java
src/main/java/com/example/finalproj/config/S3Config.java
src/main/java/com/example/finalproj/config/WebConfig.java
src/main/java/com/example/finalproj/user/controller/UserController.java
src/main/java/com/example/finalproj/user/service/UserService.java

[Branch][feature/eunCodeFix]
- 작업한 코드 정리
- 코드에 주석을 달아 설명
스크린샷을 첨부해주세요.

[코드 정리] 작성 코드 정리

---

http/calendarPhoto.http
http/calendarPhotoInf.http
src/main/java/com/example/finalproj/CalendarPhotoInf/service/CalendarPhotoInfService.java
src/main/java/com/example/finalproj/ml/service/MLService.java
src/main/resources/application.yml

[Branch][feature/calendarPhotoNoteAdd]
- 캘린더 추론 결과 key 값 변경 -> notes 값을 title 컬럼에 받음
스크린샷을 첨부해주세요.
- #39 

[기능 개선] 캘린더 추론 결과 key 값 변경 -> notes 값을 title 컬럼에 받음

---

http/page.http
src/main/java/com/example/finalproj/Book/service/BookService.java
src/main/java/com/example/finalproj/CalendarPhoto/service/CalendarPhotoService.java
src/main/java/com/example/finalproj/ml/BookML/BookMLEventListener.java
src/main/java/com/example/finalproj/ml/BookML/BookMLProcessingCompletedEvent.java
src/main/java/com/example/finalproj/ml/BookML/BookMLService.java
src/main/java/com/example/finalproj/ml/CalendarML/CalendarMLEventListener.java
src/main/java/com/example/finalproj/ml/CalendarML/CalendarMLProcessingCompletedEvent.java
src/main/java/com/example/finalproj/ml/CalendarML/CalendarMLService.java

[Branch][feature/MLFolder]
- 각각 브랜치 작업 중 충돌을 방지하기 위해 ML서버와 관련된 코드를 분리.
- closed #41 

[폴더 구성 수정] MLFolder Edit

---

src/main/java/com/example/finalproj/config/WebConfig.java
src/main/java/com/example/finalproj/user/controller/UserController.java
src/main/resources/application.yml

[Branch][fix/update-origins-and-logging]
- dev서버 cors문제, 디버깅용 코드
- 구글로그인 컨트롤러(user/controller/UserController.java)에 디버그용 로깅, 몇가지 예외처리 추가
- application.yml파일에 디버그 경로(구글로그인 부분) 추가
- WebConfig.java 모든 origin 허용
스크린샷을 첨부해주세요.
- 로그인 컨트롤러부분 괜찮은지 봐주세용

[기능 수정] 모든 오리진 허용, google login부분 로깅 추가 

---

http/calendar.http
http/calendarPhoto.http
src/main/java/com/example/finalproj/CalendarPhotoInf/service/CalendarPhotoInfService.java
src/main/java/com/example/finalproj/calendar/controller/CalendarController.java
src/main/java/com/example/finalproj/calendar/entity/Calendar.java
src/main/java/com/example/finalproj/calendar/repository/CalendarRepository.java
src/main/java/com/example/finalproj/calendar/service/CalendarService.java
src/main/java/com/example/finalproj/ml/CalendarML/CalendarMLEventListener.java
src/main/resources/init.sql

[Branch][feature/calendarDBColumnAdd]
- 추론 결과가 고도화 됨에 따라 백에서 받아야 하는 값이 늘어남
- calendar 테이블 컬럼에 information, notes 를 추가하여 추론 결과 배치
스크린샷을 첨부해주세요.
- closed #39 

[기능 개선] calendar 컬럼 추가 (information, notes), 추론 결과 처리

---

build.gradle
src/main/java/com/example/finalproj/CalendarPhotoInf/controller/CalendarPhotoInfController.java
src/main/java/com/example/finalproj/CalendarPhotoInf/repository/CalendarPhotoInfRepository.java
src/main/java/com/example/finalproj/CalendarPhotoInf/service/CalendarPhotoInfService.java
src/main/java/com/example/finalproj/user/controller/UserController.java
src/main/java/com/example/finalproj/user/entity/User.java
src/main/java/com/example/finalproj/user/repository/UserRepository.java
src/main/java/com/example/finalproj/user/service/UserService.java

[Branch][feature/findloginerror]
- 로그인 시 토큰 처리하는 방식이 현재 프론트와 달라 변경
- UserController,service 변경
- google OAuth 에 맞는 개인정보 처리방침 생성
- CalendarPhotoInf  findById 생성
스크린샷을 첨부해주세요.
- close #46 

[기능 수정] User 구글 로그인에 관한 내용 전면 수정 & CalendarPhotoInf  findById 생성

---

src/main/resources/application.yml

[Branch][feature/springsecurityPassword]
- .yml 설정
- .env 추가 필요
스크린샷을 첨부해주세요.

[보안] springsecurity 패스워드 환경변수 설정

---

src/main/java/com/example/finalproj/user/controller/UserController.java

[기능수정] UserController 더미데이터 생성( userId 5, babyId 6 )

---

src/main/java/com/example/finalproj/user/controller/UserController.java
src/main/java/com/example/finalproj/user/entity/User.java
src/main/java/com/example/finalproj/user/repository/UserRepository.java
src/main/java/com/example/finalproj/user/service/UserService.java

[기능 수정]0925 edit User

---

src/main/java/com/example/finalproj/AlimInf/entity/AlimInf.java
src/main/java/com/example/finalproj/AlimInf/repository/AlimInfRepository.java
src/main/java/com/example/finalproj/AlimInf/service/AlimInfService.java
src/main/java/com/example/finalproj/Book/controller/BookController.java
src/main/java/com/example/finalproj/Book/service/BookService.java
src/main/java/com/example/finalproj/config/auth/SecurityConfig.java
src/main/java/com/example/finalproj/user/service/UserService.java

[기능 수정]alim, book, security, userService 프론트와 맞게 변경

---

http/alimInf.http
src/main/java/com/example/finalproj/AlimInf/controller/AlimInfController.java
src/main/java/com/example/finalproj/AlimInf/repository/AlimInfRepository.java
src/main/java/com/example/finalproj/AlimInf/service/AlimInfService.java
src/main/java/com/example/finalproj/config/auth/SecurityConfig.java

[Branch][Feature/alimInfGetbyalimIdApi]
- 프론트에서 알림장 추론결과를 띄우기 위해 alimId를 이용하여 추론결과 조회
- alimId를 이용한 alimInf 조회 api 생성
- http://localhost:8080/api/alim-inf/alim-inf/${alimId}
- 

[기능 개선] alimId를 이용한 alimInf 조회

---

src/main/java/com/example/finalproj/Chat/controller/ChatController.java
src/main/java/com/example/finalproj/Chat/entity/ChatMessageDTO.java
src/main/java/com/example/finalproj/Chat/repository/ChatRepository.java
src/main/java/com/example/finalproj/Chat/service/ChatService.java
src/main/java/com/example/finalproj/config/auth/SecurityConfig.java
src/main/java/com/example/finalproj/ml/ChatML/ChatMLService.java
src/main/java/com/example/finalproj/user/service/UserService.java

[Branch][feature/editdiaryandchatbot]
- 챗봇과 프론트 부분 api연결 
스크린샷을 첨부해주세요.
- close #62 

[기능 생성] chat controller 생성

---

src/main/resources/application.yml
src/main/resources/init.sql

[Branch][feature/dbSchma]
- 작업 중 db 수정으로 rds에 정리가 되지않은 db 저장되어있었음(ex, 대문자 테이블, 소문자 테이블)
- dbSchema 정리, 수정
- 현재 에러가 생기지 않는 범위에서 수정하였으며 향후 연관되지 않은 fk 제거 필요
스크린샷을 첨부해주세요.
- (https://www.notion.so/3-043cc602096f429b943c285744c635d5?p=361d5c4638a942199ad039b3adff1c97&pm=s)

[DB 수정] dbSchema 정리, 수정

---

http/book.http
http/page.http
src/main/java/com/example/finalproj/Book/controller/BookController.java
src/main/java/com/example/finalproj/Book/entity/Book.java
src/main/java/com/example/finalproj/Book/service/BookService.java
src/main/java/com/example/finalproj/Page/entity/Page.java

[Branch][feature/fairyinquiry]
- Book 조회가 안되고 있어서 코드 수정을 했습니다
- Book 조회 수정

[기능 보완] Book 조회 수정

---

src/main/java/com/example/finalproj/AlimInf/entity/AlimInf.java
src/main/java/com/example/finalproj/AlimInf/service/AlimInfService.java

[Branch][feature/alimInfDBEditToBook]
- 알림장 추론 결과를 받아왔을 때 name이 null이면 babyId를 이용해서 babyName을 가져와서 name에 저장함
스크린샷을 첨부해주세요.

[기능 생성] 알림장 결과 부분에서 name 들어가게 설정 

---

src/main/java/com/example/finalproj/config/auth/CustomOAuth2UserService.java
src/main/java/com/example/finalproj/config/auth/OAuthAttributes.java
src/main/java/com/example/finalproj/config/auth/dto/SessionUser.java
src/main/java/com/example/finalproj/security/JwtTokenProvider.java
src/main/java/com/example/finalproj/user/controller/UserController.java
src/main/java/com/example/finalproj/user/service/UserService.java
src/main/resources/application.yml

[Branch][Feature/security]
- 구글에서 받아온 토큰값을 사용하여 인증하고 사용자 정보를 호출한다.
스크린샷을 첨부해주세요.
- closed #34

[기능 생성] security 처리

---

src/main/java/com/example/finalproj/BabyPhoto/controller/BabyPhotoController.java
src/main/java/com/example/finalproj/BabyPhoto/repository/BabyPhotoRepository.java
src/main/java/com/example/finalproj/BabyPhoto/service/BabyPhotoService.java
src/main/java/com/example/finalproj/Chat/controller/ChatController.java
src/main/java/com/example/finalproj/Chat/entity/ChatMessageDTO.java
src/main/java/com/example/finalproj/Chat/repository/ChatRepository.java
src/main/java/com/example/finalproj/Chat/service/ChatService.java
src/main/java/com/example/finalproj/config/auth/SecurityConfig.java
src/main/java/com/example/finalproj/ml/ChatML/ChatMLService.java
src/main/java/com/example/finalproj/user/service/UserService.java

[기능 수정] chatbot, baby 수정 api 수정

---

src/main/java/com/example/finalproj/user/controller/UserController.java

[Hot fix]fix : frontUrl 환경변수 설정 수정

---

build.gradle
src/main/java/com/example/finalproj/BabyPhoto/controller/BabyPhotoController.java
src/main/java/com/example/finalproj/BabyPhoto/repository/BabyPhotoRepository.java
src/main/java/com/example/finalproj/BabyPhoto/service/BabyPhotoService.java
src/main/java/com/example/finalproj/Chat/controller/ChatController.java
src/main/java/com/example/finalproj/config/WebConfig.java
src/main/java/com/example/finalproj/security/JwtAuthenticationFilter.java
src/main/java/com/example/finalproj/security/JwtTokenProvider.java

[Branch][feature/editchatandjwt]
- 구글로그인으로 chatbot 사용 시 token을 담아 ml에 전송
- BabyPhotoController
- Jwt 필터링 추가 및 변경
- jaxb gradle 추가
- ChatController 토큰설정
- 로그인 시
- 챗봇 사용 시
-JAXB 에러가 계속 나서 gradle 추가
- #73 
- s3에 담겨있는 사진을 못가져옵니다. 구글링 해보니 s3 버킷 권한과 cors 설정을 해줘야 한다고 하는데 맞을까요?!

[기능 수정]0928 BabyPhotoController, Jwt 필터링, jaxb gradle 추가 및 ChatController 토큰설정

---

src/main/java/com/example/finalproj/Alim/controller/AlimController.java
src/main/java/com/example/finalproj/Alim/entity/Alim.java
src/main/java/com/example/finalproj/AlimInf/repository/AlimInfRepository.java
src/main/java/com/example/finalproj/AlimInf/service/AlimInfService.java
src/main/java/com/example/finalproj/config/auth/SecurityConfig.java

[Branch][findLatestByAlimId]
- NonUniqueResultException 에러 해결
스크린샷을 첨부해주세요.

0930 commit - NonUniqueResultException 해결

---

src/main/java/com/example/finalproj/TodaySum/controller/TodaySumController.java
src/main/java/com/example/finalproj/TodaySum/entity/TodaySum.java
src/main/java/com/example/finalproj/TodaySum/repository/TodaySumRepository.java
src/main/java/com/example/finalproj/TodaySum/service/TodaySumService.java

[Branch][feature/todaysum]
- 챗봇 사용 후 일기 생성시 ML에서 전송된 일기를 저장하기 위해 db컬럼 수정
스크린샷을 첨부해주세요.

[기능 수정] todaySum db Edit (st,en, ge,re,date -> date)

---

src/main/java/com/example/finalproj/TodaySum/entity/TodaySum.java
src/main/java/com/example/finalproj/TodaySum/service/TodaySumService.java

[기능수정] fix : todaySum DB bookId -> babyId

---

src/main/java/com/example/finalproj/TodaySum/controller/TodaySumController.java

[기능 수정] json -> db schema save

---

src/main/java/com/example/finalproj/Book/controller/BookController.java
src/main/java/com/example/finalproj/ml/BookML/BookMLService.java
src/main/resources/application.yml

[Branch][feature/status]
- null값 허용과 rds
- BookController, BookMLSerivce에 동화 생성 상태를 볼 수 있는 코드 추가 + null값 허용 / application.yml 수정
스크린샷을 첨부해주세요.
- null값 허용과 rds

[기능 수정] 동화 생성 상태를 볼 수 있는 코드 추가+ rds 관련

---

src/main/resources/init.sql

[Branch][feature/todaysum-db]
- todaysum db 변경되어 init.sql 변경
스크린샷을 첨부해주세요.

[DB 수정] init.sql 수정

---

src/main/java/com/example/finalproj/Alim/entity/Alim.java
src/main/resources/init.sql

[Branch][Feature/alimContextToTEXT]
- 알림장 입력이 255자 까지밖에 저장이 안됨
- 더 길게 작성하고 싶기 때문에
- 알림 db의 Context 부분 유형을 TEXT로 수정
스크린샷을 첨부해주세요.

[DB 수정] 알림 db의 Context 부분 유형을 TEXT로 수정

---

http/babyPhoto.http
src/main/java/com/example/finalproj/BabyPhoto/controller/BabyPhotoController.java
src/main/java/com/example/finalproj/BabyPhoto/entity/BabyPhoto.java
src/main/java/com/example/finalproj/BabyPhoto/repository/BabyPhotoRepository.java
src/main/java/com/example/finalproj/BabyPhoto/service/BabyPhotoService.java
src/main/java/com/example/finalproj/Chat/controller/ChatController.java
src/main/java/com/example/finalproj/Chat/entity/ChatMessageDTO.java
src/main/java/com/example/finalproj/Chat/service/ChatService.java
src/main/java/com/example/finalproj/baby/controller/BabyController.java
src/main/java/com/example/finalproj/baby/service/BabyService.java
src/main/java/com/example/finalproj/ml/ChatML/ChatMLService.java
src/main/java/com/example/finalproj/user/controller/UserController.java
src/main/java/com/example/finalproj/user/repository/UserRepository.java
src/main/java/com/example/finalproj/user/service/UserService.java

[Branch][feature/editgooglegjwt]
스크린샷을 첨부해주세요.

[기능 수정] chatbot mlService 기능 동작 및 baby-photo 변경

---

src/main/java/com/example/finalproj/auth/jwt/JwtAuthenticationFilter.java

[Branch][feature/jwt]
- 클라이언트 요청 헤더에 jwt가 포함되어 있지 않다면 401에러 반환
스크린샷을 첨부해주세요.

[기능 개선] 클라이언트 요청 헤더에 jwt가 포함되어 있지 않다면 401에러 반환

---

src/main/java/com/example/finalproj/auth/jwt/JwtAuthenticationFilter.java
src/main/java/com/example/finalproj/auth/jwt/JwtTokenProvider.java
src/main/java/com/example/finalproj/auth/jwt/RefreshToken/RefreshToken.java
src/main/java/com/example/finalproj/auth/jwt/RefreshToken/RefreshTokenRepository.java
src/main/java/com/example/finalproj/auth/jwt/RefreshToken/RefreshTokenService.java
src/main/java/com/example/finalproj/config/SecurityConfig.java
src/main/resources/application.yml

[Branch][Feature/filter error]
- refreshtoken 이용하여 accesstoken 가져오기
- refreshtoken 만료시 재로그인
-
스크린샷을 첨부해주세요.

[기능 개선] 로그인 기능 개선

---

http/book.http
src/main/java/com/example/finalproj/domain/book/cover/controller/BookController.java
src/main/java/com/example/finalproj/domain/book/cover/entity/Book.java
src/main/java/com/example/finalproj/domain/book/cover/repository/BookRepository.java
src/main/java/com/example/finalproj/domain/book/cover/service/BookService.java
src/main/java/com/example/finalproj/domain/chat/diary/controller/TodaySumController.java
src/main/java/com/example/finalproj/domain/chat/diary/repository/TodaySumRepository.java
src/main/java/com/example/finalproj/domain/chat/diary/service/TodaySumService.java

[Branch][featyre/babyuserid]
- 특정 사용자와 아기에 대한 책 목록 조회가 되게 하고싶어서
- TodaySum도 특정 사용자와 아기에 대한 책 목록 조회하게 하고싶어서
Book DB에 babyId를 추가하고 book api 추가 및 변경
-------------------------변경점----------------------------------

[기능 생성] 특정 사용자와 아기에 대한 책 목록 조회

---

src/main/java/com/example/finalproj/config/SchedulerConfig.java
src/main/java/com/example/finalproj/domain/chat/context/service/ChatService.java
src/main/java/com/example/finalproj/ml/chatML/ChatMLService.java
src/main/java/com/example/finalproj/redis/service/RedisChatService.java

[Branch][feature/editrediswithchatbot]
스크린샷을 첨부해주세요.
- #73 

[기능 수정] redis에서 자정마다 db로 데이터 전송 및 redis 초기화

---

src/main/java/com/example/finalproj/domain/baby/original/entity/Baby.java
src/main/java/com/example/finalproj/domain/baby/original/service/BabyService.java
src/main/java/com/example/finalproj/domain/book/cover/repository/BookRepository.java
src/main/java/com/example/finalproj/domain/calendar/newsletter/inference/repository/CalendarPhotoInfRepository.java
src/main/java/com/example/finalproj/domain/chat/context/repository/ChatRepository.java
src/main/java/com/example/finalproj/domain/chat/diary/repository/TodaySumRepository.java
src/main/java/com/example/finalproj/domain/memo/repository/MemoRepository.java
src/main/java/com/example/finalproj/domain/notice/inference/repository/AlimInfRepository.java
src/main/java/com/example/finalproj/domain/notice/original/repository/AlimRepository.java
src/main/resources/application.yml

[기능 수정] 아이 삭제 service

---

src/main/java/com/example/finalproj/domain/baby/photo/controller/BabyPhotoController.java
src/main/java/com/example/finalproj/domain/baby/photo/service/BabyPhotoService.java

[Branch][feature/babyPhotoPut]
- 아기 사진 수정 기능 에러 수정됨
(기존 에러는 아기 사진이 없는 경우 Put api 내 에서 기존 사진을 찾을 수 없어서 발생함)
스크린샷을 첨부해주세요.

[기능 수정] babyPhoto Put Error Edit

---

src/main/java/com/example/finalproj/domain/chat/context/entity/ChatMessageDTO.java
src/main/java/com/example/finalproj/ml/chatML/ChatMLService.java
src/main/resources/application.yml

[기능 수정]1006 chat controller role 생성

---

src/main/java/com/example/finalproj/config/SecurityConfig.java
src/main/java/com/example/finalproj/domain/user/controller/UserController.java

[Branch][feature/valiedToken]
- 미들웨어 token 인증 api
스크린샷을 첨부해주세요.

[기능 생성] middleware token 인증 api

---

src/main/java/com/example/finalproj/config/WebConfig.java
src/main/java/com/example/finalproj/domain/chat/context/repository/ChatRepository.java
src/main/java/com/example/finalproj/domain/chat/context/service/ChatService.java
src/main/java/com/example/finalproj/ml/chatML/ChatMLService.java
src/main/java/com/example/finalproj/redis/service/RedisChatService.java
src/main/resources/application.yml

[기능 수정] chatbot history and response 수정

---

src/main/java/com/example/finalproj/domain/book/cover/controller/BookController.java
src/main/java/com/example/finalproj/ml/calendarML/CalendarMLEventListener.java

[Branch][feature/bookInfLogEdit]
- 동화 생성 결과 로그가 너무 길어서 로그에 뜨지 않게 수정 
- 생성시 "동화생성 성공", 실패시 "동화생성 실패"
스크린샷을 첨부해주세요.

[로그 개선] 동화 생성 로그에 동화 생성 결과 안뜨게 함

---

src/main/java/com/example/finalproj/domain/chat/context/controller/ChatController.java
src/main/java/com/example/finalproj/domain/chat/context/service/ChatService.java
src/main/java/com/example/finalproj/domain/chat/diary/controller/TodaySumController.java
src/main/java/com/example/finalproj/domain/chat/diary/repository/TodaySumRepository.java
src/main/java/com/example/finalproj/domain/chat/diary/service/TodaySumService.java
src/main/java/com/example/finalproj/ml/chatML/ChatMLService.java

[기능 수정] chatbot 일기, 일기목록 추가,수정

---

src/main/java/com/example/finalproj/domain/notice/original/controller/AlimController.java
src/main/java/com/example/finalproj/domain/notice/original/repository/AlimRepository.java
src/main/java/com/example/finalproj/domain/notice/original/service/AlimService.java

[기능 수정] AlimController userId별 babyId별로 조회

---

src/main/java/com/example/finalproj/config/SecurityConfig.java

[Branch][feature/voiceAuthError]
-  /api/voice-memo security 제외
스크린샷을 첨부해주세요.

[auth 제외] /api/voice-memo security 제외
